on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Setup Go 1.18'
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Run Go Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-cache: true

      - name: Run go tests
        run: |
          go test ./...
