name: Continuous Integration

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    name: 'Run linter'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Setup Go 1.18'
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Run Generate Code
        run: |
          go generate ./...

      - name: Run Go Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-cache: true

  test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Setup Go 1.18'
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Run Generate Code
        run: |
          go generate ./...

      - name: Run go tests
        run: |
          go test ./...

  checks-passed:
    name: 'Checks passed'
    needs:
      [
        lint,
        test
      ]
    runs-on: 'ubuntu-latest'
    steps:
      - name: Done
        run: echo 'Checks passed'
