// Code generated by qtc from "list.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/list.qtpl:1
package view

//line view/list.qtpl:1
import "github.com/sparkymat/files/internal/presenter"

//line view/list.qtpl:2
import "github.com/sparkymat/files/config"

//line view/list.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/list.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/list.qtpl:4
func streamconfigAction(qw422016 *qt422016.Writer, icon string, tooltip string, viewType string, returnPath string) {
//line view/list.qtpl:4
	qw422016.N().S(`
  <a
    href="/update_config"
    data-method="post"
    data-remote="true"
    data-params="viewType=`)
//line view/list.qtpl:9
	qw422016.N().U(viewType)
//line view/list.qtpl:9
	qw422016.N().S(`&returnPath=`)
//line view/list.qtpl:9
	qw422016.N().U(returnPath)
//line view/list.qtpl:9
	qw422016.N().S(`"
    >
    <i class="material-icons tooltipped" data-position="bottom" data-tooltip="`)
//line view/list.qtpl:11
	qw422016.E().S(tooltip)
//line view/list.qtpl:11
	qw422016.N().S(`">`)
//line view/list.qtpl:11
	qw422016.E().S(icon)
//line view/list.qtpl:11
	qw422016.N().S(`</i>
  </a>
`)
//line view/list.qtpl:13
}

//line view/list.qtpl:13
func writeconfigAction(qq422016 qtio422016.Writer, icon string, tooltip string, viewType string, returnPath string) {
//line view/list.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/list.qtpl:13
	streamconfigAction(qw422016, icon, tooltip, viewType, returnPath)
//line view/list.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line view/list.qtpl:13
}

//line view/list.qtpl:13
func configAction(icon string, tooltip string, viewType string, returnPath string) string {
//line view/list.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
//line view/list.qtpl:13
	writeconfigAction(qb422016, icon, tooltip, viewType, returnPath)
//line view/list.qtpl:13
	qs422016 := string(qb422016.B)
//line view/list.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
//line view/list.qtpl:13
	return qs422016
//line view/list.qtpl:13
}

//line view/list.qtpl:15
func StreamList(qw422016 *qt422016.Writer, list presenter.List) {
//line view/list.qtpl:15
	qw422016.N().S(`
  <div class="container-fluid">
    <div class="row">
      <nav class="col s12 blue">
        <div class="nav-wrapper">
          <div class="col s12 l9">
            `)
//line view/list.qtpl:21
	for _, pathSegment := range list.PathSegments {
//line view/list.qtpl:21
		qw422016.N().S(`
              <a href="`)
//line view/list.qtpl:22
		qw422016.E().S(pathSegment.Path)
//line view/list.qtpl:22
		qw422016.N().S(`" class="breadcrumb">`)
//line view/list.qtpl:22
		qw422016.E().S(pathSegment.Label)
//line view/list.qtpl:22
		qw422016.N().S(`</a>
            `)
//line view/list.qtpl:23
	}
//line view/list.qtpl:23
	qw422016.N().S(`
          </div>
          <div class="col s12 l3 hide-on-med-and-down">
            <ul class="right">
              `)
//line view/list.qtpl:27
	if list.ShowGridButton {
//line view/list.qtpl:27
		qw422016.N().S(`
                <li>`)
//line view/list.qtpl:28
		streamconfigAction(qw422016, "view_module", "Switch to grid view", "grid", list.CurrentPath)
//line view/list.qtpl:28
		qw422016.N().S(`</li> 
              `)
//line view/list.qtpl:29
	}
//line view/list.qtpl:29
	qw422016.N().S(`
              `)
//line view/list.qtpl:30
	if list.ShowListButton {
//line view/list.qtpl:30
		qw422016.N().S(`
                <li>`)
//line view/list.qtpl:31
		streamconfigAction(qw422016, "view_list", "Switch to list view", "list", list.CurrentPath)
//line view/list.qtpl:31
		qw422016.N().S(`</li> 
              `)
//line view/list.qtpl:32
	}
//line view/list.qtpl:32
	qw422016.N().S(`
            </ul>
          </div>
        </div>
      </nav>
      `)
//line view/list.qtpl:37
	if list.ViewType == config.ViewList {
//line view/list.qtpl:37
		qw422016.N().S(`
        <table class="col s12">
          <thead>
            <tr>
              <th>Name</th>
              <th>Type</th>
              <th>Size</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            `)
//line view/list.qtpl:48
		for _, entry := range list.Entries {
//line view/list.qtpl:48
			qw422016.N().S(`
              <tr>
                <td>
                  `)
//line view/list.qtpl:51
			if entry.Linkable {
//line view/list.qtpl:51
				qw422016.N().S(`
                    <a class="`)
//line view/list.qtpl:52
				qw422016.E().S(entry.LinkClass)
//line view/list.qtpl:52
				qw422016.N().S(`" href="`)
//line view/list.qtpl:52
				qw422016.E().S(entry.Path)
//line view/list.qtpl:52
				qw422016.N().S(`">
                  `)
//line view/list.qtpl:53
			} else {
//line view/list.qtpl:53
				qw422016.N().S(`
                    <div>
                  `)
//line view/list.qtpl:55
			}
//line view/list.qtpl:55
			qw422016.N().S(`
                    <span class="entry-row">
                      <i class="material-icons">`)
//line view/list.qtpl:57
			qw422016.E().S(entry.MaterialIcon)
//line view/list.qtpl:57
			qw422016.N().S(`</i>
                      `)
//line view/list.qtpl:58
			qw422016.E().S(entry.Label)
//line view/list.qtpl:58
			qw422016.N().S(`
                    </span>
                  `)
//line view/list.qtpl:60
			if entry.Linkable {
//line view/list.qtpl:60
				qw422016.N().S(`
                    </a>
                  `)
//line view/list.qtpl:62
			} else {
//line view/list.qtpl:62
				qw422016.N().S(`
                    </div>
                  `)
//line view/list.qtpl:64
			}
//line view/list.qtpl:64
			qw422016.N().S(`
                </td>
                <td>`)
//line view/list.qtpl:66
			qw422016.E().S(entry.Type)
//line view/list.qtpl:66
			qw422016.N().S(`</td>
                <td>`)
//line view/list.qtpl:67
			qw422016.E().S(entry.Size)
//line view/list.qtpl:67
			qw422016.N().S(`</td>
                <td>
                  <a href="`)
//line view/list.qtpl:69
			qw422016.E().S(entry.Path)
//line view/list.qtpl:69
			qw422016.N().S(`" target="_blank">
                    <i class="material-icons">file_download</i>
                  </a>
                </td>
              </tr>
            `)
//line view/list.qtpl:74
		}
//line view/list.qtpl:74
		qw422016.N().S(`
          </tbody>
        </table>
      `)
//line view/list.qtpl:77
	} else if list.ViewType == config.ViewGrid {
//line view/list.qtpl:77
		qw422016.N().S(`
        <div class="col s12">
          `)
//line view/list.qtpl:79
		for _, entry := range list.Entries {
//line view/list.qtpl:79
			qw422016.N().S(`
            `)
//line view/list.qtpl:80
			if entry.Linkable {
//line view/list.qtpl:80
				qw422016.N().S(`
              <a class="`)
//line view/list.qtpl:81
				qw422016.E().S(entry.LinkClass)
//line view/list.qtpl:81
				qw422016.N().S(`" href="`)
//line view/list.qtpl:81
				qw422016.E().S(entry.Path)
//line view/list.qtpl:81
				qw422016.N().S(`">
            `)
//line view/list.qtpl:82
			} else {
//line view/list.qtpl:82
				qw422016.N().S(`
              <div>
            `)
//line view/list.qtpl:84
			}
//line view/list.qtpl:84
			qw422016.N().S(`
              <div class="col s4 l2 entry-grid">
                    <i class="material-icons large">`)
//line view/list.qtpl:86
			qw422016.E().S(entry.MaterialIcon)
//line view/list.qtpl:86
			qw422016.N().S(`</i>
                    `)
//line view/list.qtpl:87
			qw422016.E().S(entry.Label)
//line view/list.qtpl:87
			qw422016.N().S(`
              </div>
            `)
//line view/list.qtpl:89
			if entry.Linkable {
//line view/list.qtpl:89
				qw422016.N().S(`
              </a>
            `)
//line view/list.qtpl:91
			} else {
//line view/list.qtpl:91
				qw422016.N().S(`
              </div>
            `)
//line view/list.qtpl:93
			}
//line view/list.qtpl:93
			qw422016.N().S(`
          `)
//line view/list.qtpl:94
		}
//line view/list.qtpl:94
		qw422016.N().S(`
        </div>
      `)
//line view/list.qtpl:96
	}
//line view/list.qtpl:96
	qw422016.N().S(`
    </div>
  </div>
`)
//line view/list.qtpl:99
}

//line view/list.qtpl:99
func WriteList(qq422016 qtio422016.Writer, list presenter.List) {
//line view/list.qtpl:99
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/list.qtpl:99
	StreamList(qw422016, list)
//line view/list.qtpl:99
	qt422016.ReleaseWriter(qw422016)
//line view/list.qtpl:99
}

//line view/list.qtpl:99
func List(list presenter.List) string {
//line view/list.qtpl:99
	qb422016 := qt422016.AcquireByteBuffer()
//line view/list.qtpl:99
	WriteList(qb422016, list)
//line view/list.qtpl:99
	qs422016 := string(qb422016.B)
//line view/list.qtpl:99
	qt422016.ReleaseByteBuffer(qb422016)
//line view/list.qtpl:99
	return qs422016
//line view/list.qtpl:99
}
